build(cdviz-db): fix "turn on the containerd image store"
```
ERROR: Attestation is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
```